### ISSUE TITLE
Make datasource and delegate to be of the correct type.

### ISSUE THREAD

**Issue by Sweeper777** [sasojadrovski/SJFluidSegmentedControl#7]
Currently, both the `datasource` property and the `delegate` property are of type `AnyObject?`. Why not change them to be of type `SJFluidSegmentedControlDatasource?` and `SJFluidSegmentedControlDelegate?` respectively? This way errors can be detected at compile time.

**Comment by sasojadrovski** [comment]
Hi @Sweeper777,

The `dataSource` and `delegate` properties are set to `AnyObject?` type because they are exposed to interface builder as `@IBOutlet` properties, therefore they cannot have a `non-'@objc'` protocol type, such as `SJFluidSegmentedControlDataSource` or `SJFluidSegmentedControlDelegate`.
